### ISSUE TITLE
quantities does not work with unique() in tibbles

### ISSUE THREAD

**Issue by vorpalvorpal** [r-quantities/quantities#12]
```
df <- tribble(
  ~a, ~b,
  "foo", set_quantities(1, mm, 1),
  "foo", set_quantities(1, mm, 1)
)
unique(df)
A tibble: 2 x 2
  a              b
  <chr> ± err [mm]
1 foo        1 ± 1
2 foo        1 ± 1
```

I had a more complex tibble with quantities where calling unique() wasn't working so I tested "df[1,] == df[2,]" and got the following error:

Warning message:
In '==' : boolean operators not defined for 'errors' objects, uncertainty dropped 

However, I can't seem to get this error again with the minimal working example above even though unique() isn't working correctly.

**Comment by Enchufa2** [comment]
Thanks, `unique` was only recently added to `units`, we'll need to implement this method for `quantities` and `errors` too.

**Comment by Enchufa2** [comment]
Unfortunately, calling `unique` on the whole data frame still won't work. This is due to how `unique.data.frame` works, and we can't do anything about it. However, since we have now a method for `duplicated`, you can do this:

``` r
library(quantities)
#> Loading required package: units
#> udunits database from /usr/share/udunits/udunits2.xml
#> Loading required package: errors

df <- tibble::tribble(
  ~a, ~b,
  "foo", set_quantities(1, mm, 1),
  "foo", set_quantities(1, mm, 1)
)

unique_quantities <- function(df, ...) {
  dup <- rowSums(sapply(df, duplicated, ...)) == ncol(df)
  df[dup, ]
}

unique_quantities(df)
#> # A tibble: 1 × 2
#>   a              b
#>   <chr> (err) [mm]
#> 1 foo         1(1)
```
